- hosts: localhost
  name: Isilon New SMB share with URI module
  tasks:
  - name: get isilon API session IDs
    register: results_login
    uri:
      body:
        password: a
        services:
        - platform
        - namespace
        username: root
      body_format: json
      method: POST
      status_code: 201
      url: https://172.16.10.10:8080/session/1/session
      validate_certs: false
  - name: make SMB share
    uri:
      body:
        browsable: true
        create_path: true
        description: example share
        name: example1
        path: /ifs/example1
        permissions:
        - permission: full
          permission_type: allow
          trustee:
            name: root
            type: user
        zone: system
      body_format: json
      headers:
        Cookie: isisessid={{ results_login.cookies.isisessid }}
        X-CSRF-Token: '{{ results_login.cookies.isicsrf }}'
        referer: https://172.16.10.10:8080
      method: POST
      status_code: 201
      url: https://172.16.10.10:8080/platform/4/protocols/smb/shares
      validate_certs: false
  - name: make SMB share
    uri:
      body:
        browsable: true
        create_path: true
        description: example share
        name: example2
        path: /ifs/example2
        permissions:
        - permission: full
          permission_type: allow
          trustee:
            name: root
            type: user
        zone: system
      body_format: json
      headers:
        Cookie: isisessid={{ results_login.cookies.isisessid }}
        X-CSRF-Token: '{{ results_login.cookies.isicsrf }}'
        referer: https://172.16.10.10:8080
      method: POST
      status_code: 201
      url: https://172.16.10.10:8080/platform/4/protocols/smb/shares
      validate_certs: false
  - name: make SMB share
    uri:
      body:
        browsable: true
        create_path: true
        description: example share
        name: example3
        path: /ifs/example3
        permissions:
        - permission: full
          permission_type: allow
          trustee:
            name: root
            type: user
        zone: system
      body_format: json
      headers:
        Cookie: isisessid={{ results_login.cookies.isisessid }}
        X-CSRF-Token: '{{ results_login.cookies.isicsrf }}'
        referer: https://172.16.10.10:8080
      method: POST
      status_code: 201
      url: https://172.16.10.10:8080/platform/4/protocols/smb/shares
      validate_certs: false
  - name: Delete isilon API session IDs
    register: results_DEL_cookie
    uri:
      headers:
        Cookie: isisessid={{ results_login.cookies.isisessid }}
        X-CSRF-Token: '{{ results_login.cookies.isicsrf }}'
        referer: https://172.16.10.10:8080
      method: DELETE
      status_code: 204
      url: https://172.16.10.10:8080/session/1/session
      validate_certs: false
